lib/task_tracker_web/router.ex
defmodule TaskTrackerWeb.Router do
  use TaskTrackerWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug TaskTrackerWeb.Plugs.FetchSession
  end

  pipeline :ajax do
    plug :accepts, ["json"]
    plug :fetch_session
    plug :fetch_flash
    plug TaskTrackerWeb.Plugs.FetchSession
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", TaskTrackerWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    resources "/tasks", TaskController
    resources "/users", UserController
    resources "/assigned_tasks", AssignedTaskController
    resources "/assigned_users", AssignedUserController
    resources "/sessions", SessionController, only: [:create, :delete], singleton: true
  end

  scope "/ajax", TaskTrackerWeb do
    pipe_through :ajax

    resources "/time_blocks", TimeBlockController, except: [:new, :edit]
  end

  # Other scopes may use custom stacks.
  # scope "/api", TaskTrackerWeb do
  #   pipe_through :api
  # end
end

lib/task_tracker/users/user.ex
defmodule TaskTracker.Users.User do
  use Ecto.Schema
  import Ecto.Changeset


  schema "users" do
    field :email, :string
    field :admin, :boolean, default: false, null: false

    has_many :assigned_tasks, TaskTracker.AssignedTasks.AssignedTask
    has_many :assigned_users, TaskTracker.AssignedUsers.AssignedUser

    timestamps()
  end

  @doc false
  def changeset(user, attrs) do
    user
    |> cast(attrs, [:email, :admin])
    |> validate_required([:email, :admin])
  end
end

lib/task_tracker/users/users.ex
defmodule TaskTracker.Users do
  @moduledoc """
  The Users context.
  """

  import Ecto.Query, warn: false
  alias TaskTracker.Repo

  alias TaskTracker.Users.User

  @doc """
  Returns the list of users.

  ## Examples

      iex> list_users()
      [%User{}, ...]

  """
  def list_users do
    Repo.all(User)
  end

  @doc """
  Gets a single user.

  Raises `Ecto.NoResultsError` if the User does not exist.

  ## Examples

      iex> get_user!(123)
      %User{}

      iex> get_user!(456)
      ** (Ecto.NoResultsError)

  """
  def get_user!(id), do: Repo.get!(User, id)

  def get_user(id) do
    Repo.one from u in User,
      where: u.id == ^id,
      preload: [assigned_tasks: :task]
  end

  def get_user_by_email(email) do
    Repo.get_by(User, email: email)
  end

  @doc """
  Creates a user.

  ## Examples

      iex> create_user(%{field: value})
      {:ok, %User{}}

      iex> create_user(%{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def create_user(attrs \\ %{}) do
    %User{}
    |> User.changeset(attrs)
    |> Repo.insert()
  end

  @doc """
  Updates a user.

  ## Examples

      iex> update_user(user, %{field: new_value})
      {:ok, %User{}}

      iex> update_user(user, %{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def update_user(%User{} = user, attrs) do
    user
    |> User.changeset(attrs)
    |> Repo.update()
  end

  @doc """
  Deletes a User.

  ## Examples

      iex> delete_user(user)
      {:ok, %User{}}

      iex> delete_user(user)
      {:error, %Ecto.Changeset{}}

  """
  def delete_user(%User{} = user) do
    Repo.delete(user)
  end

  @doc """
  Returns an `%Ecto.Changeset{}` for tracking user changes.

  ## Examples

      iex> change_user(user)
      %Ecto.Changeset{source: %User{}}

  """
  def change_user(%User{} = user) do
    User.changeset(user, %{})
  end
end

lib/task_tracker_web/controllers/user_controller.ex
defmodule TaskTrackerWeb.UserController do
  use TaskTrackerWeb, :controller

  alias TaskTracker.Users
  alias TaskTracker.Users.User
  alias TaskTracker.AssignedUsers
  alias TaskTracker.AssignedTasks

  def index(conn, _params) do
    users = Users.list_users()
    render(conn, "index.html", users: users)
  end

  def new(conn, _params) do
    changeset = Users.change_user(%User{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"user" => user_params}) do
    case Users.create_user(user_params) do
      {:ok, user} ->
        conn
        |> put_flash(:info, "User created successfully.")
        |> put_session(:user_id, user.id)
        |> redirect(to: Routes.task_path(conn, :index))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    user = Users.get_user!(id)
    user_id = get_session(conn, :user_id)
    tasks_for_user = AssignedTasks.list_assigned_tasks_for_user(id)
    assigned_users = AssignedUsers.list_assigned_users_for_user_by_email(user.email)
    user_cset = AssignedUsers.change_assigned_user(%AssignedUsers.AssignedUser{
      user_id: id, manager_email: Users.get_user(user_id).email
    })
    reporter_tasks = Enum.map(assigned_users,
      fn user -> %{:email => user.user.email, :tasks => AssignedTasks.list_assigned_tasks_for_user(user.user_id)} end)
    manager_list = AssignedUsers.list_assigned_users_for_user(id)
    if length(manager_list) == 0 do
      render(conn, "show.html", user: user, tasks: tasks_for_user,
        user_cset: user_cset, users: assigned_users, manager: "N/A", reporter_tasks: reporter_tasks)
    else
      render(conn, "show.html", user: user, tasks: tasks_for_user,
        user_cset: user_cset, users: assigned_users, manager: (hd manager_list).manager_email,
        reporter_tasks: reporter_tasks)
    end
  end

  def edit(conn, %{"id" => id}) do
    user = Users.get_user!(id)
    changeset = Users.change_user(user)
    render(conn, "edit.html", user: user, changeset: changeset)
  end

  def update(conn, %{"id" => id, "user" => user_params}) do
    user = Users.get_user!(id)

    case Users.update_user(user, user_params) do
      {:ok, user} ->
        conn
        |> put_flash(:info, "User updated successfully.")
        |> redirect(to: Routes.user_path(conn, :show, user))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", user: user, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    user = Users.get_user!(id)
    {:ok, _user} = Users.delete_user(user)

    conn
    |> put_flash(:info, "User deleted successfully.")
    |> redirect(to: Routes.user_path(conn, :index))
  end
end

lib/task_tracker_web/views/user_view.ex
defmodule TaskTrackerWeb.UserView do
  use TaskTrackerWeb, :view
end

lib/task_tracker_web/templates/user/edit.html.eex
<h1>Edit User</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.user_path(@conn, :update, @user)) %>

<span><%= link "Back", to: Routes.user_path(@conn, :index) %></span>

lib/task_tracker_web/templates/user/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :email %>
    <%= text_input f, :email, class: "form-control" %>
    <%= error_tag f, :email %>
  </div>

  <div>
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

lib/task_tracker_web/templates/user/index.html.eex
<h1>All Users</h1>

<table class="table table-striped">
  <thead class="thead-light">
    <tr>
      <th>Email</th>
      <th>Admin?</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for user <- @users do %>
    <tr>
      <td><%= link user.email, to: Routes.user_path(@conn, :show, user) %></td>
      <td><%= user.admin %></td>

      <td>
        <%= if @current_user && @current_user.admin do %>
            <%= link "Edit", to: Routes.user_path(@conn, :edit, user), class: "btn btn-info btn-sm" %>
            <%= link "Delete", to: Routes.user_path(@conn, :delete, user), method: :delete, data: [confirm: "Are you sure?"],
                class: "btn btn-danger btn-sm" %>
        <% end %>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<span><%= link "Create New User", to: Routes.user_path(@conn, :new), class: "btn btn-primary" %></span>

lib/task_tracker_web/templates/user/new.html.eex
<h1>New User</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.user_path(@conn, :create)) %>

<span><%= link "Back", to: Routes.user_path(@conn, :index) %></span>

lib/task_tracker_web/templates/user/show.html.eex
<%= if @user.admin do %>
  <h3>Admin: <%= @user.email %></h3>
<% else %>
  <h3>Non-Admin: <%= @user.email %></h3>
<% end %>

<h4>Managed by: <%= @manager %></h4>

<h3>This user's tasks:</h3>
<table class="table table-striped">
  <thead class="thead-light">
    <tr>
      <th>Title</th>
      <th>Time Worked</th>
      <th>Complete?</th>
    </tr>
  </thead>
  <tbody>
<%= for assigned_task <- @tasks do %>
    <tr>
      <td><%= link assigned_task.task.title, to: Routes.task_path(@conn, :show, assigned_task.task) %></td>
      <td><%= assigned_task.task.time_worked %></td>
      <td><%= assigned_task.task.is_complete %></td>
    </tr>
<% end %>
  </tbody>
</table>

<h3>Users managed by this user:</h3>
<table class="table table-striped">
  <thead class="thead-light">
    <tr>
      <th>Email</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for user <- @users do %>
    <tr>
      <td><%= link user.user.email, to: Routes.user_path(@conn, :show, user.user.id) %></td>
      <td>
        <%= link "Unassign", to: Routes.assigned_user_path(@conn, :delete, user.id),
            method: :delete, data: [confirm: "Are you sure you want to unassign?"], class: "btn btn-danger btn-sm" %>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<h3>Direct Employee Task Report</h3>
<table class="table table-striped">
  <thead class="thead-light">
    <tr>
      <th>Task Name</th>
      <th>Assignee</th>
      <th>Complete?</th>
    </tr>
  </thead>
  <tbody>
<%= for reporter_task <- @reporter_tasks do %>
  <%= for task <- reporter_task.tasks do %>
    <tr>
      <td><%= link task.task.title, to: Routes.task_path(@conn, :show, task.task) %></td>
      <td><%= reporter_task.email %></td>
      <td><%= task.task.is_complete %></td>
    </tr>
  <% end %>
<% end %>
  </tbody>
</table>

<%= if @current_user && @current_user.id != @user.id do %>
  <div>
    <%= form_for @user_cset, Routes.assigned_user_path(@conn, :create), [class: "form-inline"], fn f -> %>

      <%= hidden_input f, :user_id %>
      <%= hidden_input f, :manager_email %>

      <div>
        <%= submit "Manage This User", class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
<% end %>

<% if @current_user && @current_user.admin do %>
  <span><%= link "Edit", to: Routes.user_path(@conn, :edit, @user), class: "btn btn-secondary" %></span>
<% end %>
<span><%= link "Back", to: Routes.user_path(@conn, :index) %></span>