lib/task_tracker_web/router.ex
defmodule TaskTrackerWeb.Router do
  use TaskTrackerWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug TaskTrackerWeb.Plugs.FetchSession
  end

  pipeline :ajax do
    plug :accepts, ["json"]
    plug :fetch_session
    plug :fetch_flash
    plug TaskTrackerWeb.Plugs.FetchSession
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", TaskTrackerWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    resources "/tasks", TaskController
    resources "/users", UserController
    resources "/assigned_tasks", AssignedTaskController
    resources "/assigned_users", AssignedUserController
    resources "/sessions", SessionController, only: [:create, :delete], singleton: true
  end

  scope "/ajax", TaskTrackerWeb do
    pipe_through :ajax

    resources "/time_blocks", TimeBlockController, except: [:new, :edit]
  end

  # Other scopes may use custom stacks.
  # scope "/api", TaskTrackerWeb do
  #   pipe_through :api
  # end
end

lib/task_tracker_web/views/layout_view.ex
defmodule TaskTrackerWeb.LayoutView do
  use TaskTrackerWeb, :view
end

lib/task_tracker_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, shrink-to-fit=no, user-scalable=no"/>
    <title>TaskTracker · Phoenix Framework</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
  </head>
  <body>
    <div class="container">
      <nav class="navbar navbar-expand-sm navbar-light bg-white">
        <div class="col-5">
          <a class="navbar-brand" href="/">Task Tracker</a>
        </div>
        <div class="col-2">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="/">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/users">Users</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/tasks">Tasks</a>
            </li>
          </ul>
        </div>
        <div class="col-5">
            <%= if @current_user do %>
              <p class="my-3">
                <%= link(@current_user.email, to: Routes.user_path(@conn, :show, @current_user.id)) %> |
                <%= link("Logout", to: Routes.session_path(@conn, :delete),
                  method: :delete) %>
              </p>
            <% else %>
              <%= form_for @conn, Routes.session_path(@conn, :create), [class: "form-inline"], fn f -> %>
                <%= text_input f, :email, class: "form-control" %>
                <%= submit "Login", class: "btn btn-link" %> |
                <%= link "Register", to: Routes.user_path(@conn, :new), class: "btn btn-link" %>
              <% end %>
            <% end %>
        </div>
      </nav>

      <div class="row">
        <div class="col-12">
          <%= if get_flash(@conn, :info) do %>
            <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
          <% end %>
          <%= if get_flash(@conn, :error) do %>
            <p class="alert alert-danger" role="alert">
              <%= get_flash(@conn, :error) %>
            </p>
          <% end %>
        </div>
      </div>

      <div class="row">
        <div class="col-6">
          <%= render @view_module, @view_template, assigns %>
        </div>

        <div class="col-6">
          <%= if @current_user do %>
            <%= render TaskTrackerWeb.AssignedTaskView, "index.html",
            Map.put(assigns, :assigned_tasks, @current_user.assigned_tasks) %>
          <% end %>
        </div>
      </div>
    </div>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>