lib/task_tracker_web/router.ex
defmodule TaskTrackerWeb.Router do
  use TaskTrackerWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug TaskTrackerWeb.Plugs.FetchSession
  end

  pipeline :ajax do
    plug :accepts, ["json"]
    plug :fetch_session
    plug :fetch_flash
    plug TaskTrackerWeb.Plugs.FetchSession
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", TaskTrackerWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    resources "/tasks", TaskController
    resources "/users", UserController
    resources "/assigned_tasks", AssignedTaskController
    resources "/assigned_users", AssignedUserController
    resources "/sessions", SessionController, only: [:create, :delete], singleton: true
  end

  scope "/ajax", TaskTrackerWeb do
    pipe_through :ajax

    resources "/time_blocks", TimeBlockController, except: [:new, :edit]
  end

  # Other scopes may use custom stacks.
  # scope "/api", TaskTrackerWeb do
  #   pipe_through :api
  # end
end

lib/task_tracker/tasks/task.ex
defmodule TaskTracker.Tasks.Task do
  use Ecto.Schema
  import Ecto.Changeset


  schema "tasks" do
    field :desc, :string
    field :is_complete, :boolean, default: false
    field :time_worked, :time
    field :title, :string

    has_many :assigned_tasks, TaskTracker.AssignedTasks.AssignedTask
    has_many :time_blocks, TaskTracker.TimeBlocks.TimeBlock

    timestamps()
  end

  @doc false
  def changeset(task, attrs) do
    task
    |> cast(attrs, [:title, :desc, :time_worked, :is_complete])
    |> validate_required([:title, :desc, :time_worked, :is_complete])
  end
end

lib/task_tracker/tasks/tasks.ex
defmodule TaskTracker.Tasks do
  @moduledoc """
  The Tasks context.
  """

  import Ecto.Query, warn: false
  alias TaskTracker.Repo

  alias TaskTracker.Tasks.Task

  @doc """
  Returns the list of tasks.

  ## Examples

      iex> list_tasks()
      [%Task{}, ...]

  """
  def list_tasks do
    Repo.all(Task)
  end

  @doc """
  Gets a single task.

  Raises `Ecto.NoResultsError` if the Task does not exist.

  ## Examples

      iex> get_task!(123)
      %Task{}

      iex> get_task!(456)
      ** (Ecto.NoResultsError)

  """
  def get_task!(id) do
    Repo.one! from t in Task,
      where: t.id == ^id,
      preload: [:time_blocks]
  end

  @doc """
  Creates a task.

  ## Examples

      iex> create_task(%{field: value})
      {:ok, %Task{}}

      iex> create_task(%{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def create_task(attrs \\ %{}) do
    %Task{}
    |> Task.changeset(attrs)
    |> Repo.insert()
  end

  @doc """
  Updates a task.

  ## Examples

      iex> update_task(task, %{field: new_value})
      {:ok, %Task{}}

      iex> update_task(task, %{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def update_task(%Task{} = task, attrs) do
    task
    |> Task.changeset(attrs)
    |> Repo.update()
  end

  @doc """
  Deletes a Task.

  ## Examples

      iex> delete_task(task)
      {:ok, %Task{}}

      iex> delete_task(task)
      {:error, %Ecto.Changeset{}}

  """
  def delete_task(%Task{} = task) do
    Repo.delete(task)
  end

  @doc """
  Returns an `%Ecto.Changeset{}` for tracking task changes.

  ## Examples

      iex> change_task(task)
      %Ecto.Changeset{source: %Task{}}

  """
  def change_task(%Task{} = task) do
    Task.changeset(task, %{})
  end
end

lib/task_tracker_web/controllers/task_controller.ex
defmodule TaskTrackerWeb.TaskController do
  use TaskTrackerWeb, :controller

  alias TaskTracker.Tasks
  alias TaskTracker.Tasks.Task
  alias TaskTracker.AssignedTasks
  alias TaskTracker.AssignedUsers
  alias TaskTracker.Users
  alias TaskTracker.TimeBlocks

  def index(conn, _params) do
    tasks = Tasks.list_tasks()
    render(conn, "index.html", tasks: tasks)
  end

  def new(conn, _params) do
    changeset = Tasks.change_task(%Task{})
    render(conn, "new.html", changeset: changeset, is_task_assigned_to_user: true,
      task: %{id: -1}, time_blocks: [])
  end

  def create(conn, %{"task" => task_params}) do
    task_params = Map.put(task_params, "time_worked", %{"hour" => "0", "minute" => "0"})
    case Tasks.create_task(task_params) do
      {:ok, task} ->
        conn
        |> put_flash(:info, "Task created successfully.")
        |> redirect(to: Routes.task_path(conn, :show, task))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset, task: %{id: -1}, is_task_assigned_to_user: true, time_blocks: [])
    end
  end

  def show(conn, %{"id" => id}) do
    task = Tasks.get_task!(id)
    time_blocks = TimeBlocks.list_time_blocks_for_task_id(task.id)
    user_id = get_session(conn, :user_id)
    user_email = Users.get_user(user_id).email
    users_list = AssignedUsers.list_assigned_users_for_user_by_email(user_email)
    users_list = Enum.map users_list, fn(user) -> user.user.email end
    manager_list = AssignedUsers.list_assigned_users_for_user(user_id)
    users_list =  if length(manager_list) == 0, do: users_list ++ [user_email], else: users_list
    can_assigned_to_anyone = (length(users_list) > 0)
    task_cset = AssignedTasks.change_assigned_task(%AssignedTasks.AssignedTask{
      user_id: user_id, task_id: task.id
    })
    task = if task.time_worked !== nil, do: Map.put(task, :time_worked, String.slice(Time.to_string(task.time_worked), 0, 5)), else: task
    render(conn, "show.html", task: task, task_cset: task_cset,
      users: users_list, is_task_assigned_to_user: true, can_assigned_to_anyone: can_assigned_to_anyone, time_blocks: time_blocks)
  end

  def edit(conn, %{"id" => id}) do
    task = Tasks.get_task!(id)
    time_blocks = TimeBlocks.list_time_blocks_for_task_id(task.id)
    user_id = get_session(conn, :user_id)
    assigned_task_ids = Enum.map AssignedTasks.list_assigned_tasks_for_user(user_id), fn(t) -> t.task.id end
    is_task_assigned_to_user = task.id in assigned_task_ids
    changeset = Tasks.change_task(task)
    render(conn, "edit.html", task: task, changeset: changeset, is_task_assigned_to_user: is_task_assigned_to_user,
      time_blocks: time_blocks)
  end

  def update(conn, %{"id" => id, "task" => task_params}) do
    task = Tasks.get_task!(id)
    time_blocks = TimeBlocks.list_time_blocks_for_task_id(task.id)
    time_diff = Enum.map(time_blocks, fn time -> DateTime.diff(time.end_time, time.start_time) end)
    time_in_not_sec = Enum.map(time_diff, fn time -> div(time, 60) end)
    hours = Enum.map(time_in_not_sec, fn time -> div(time, 60) end)
    minutes = Enum.map(time_in_not_sec, fn time -> rem(time, 60) end)
    total_hour = Enum.map_reduce(hours, 0, fn hour, acc -> {hour, acc + hour} end)
    total_minutes = Enum.map_reduce(minutes, 0, fn minute, acc -> {minute, acc + minute} end)
    hour = elem(total_hour, 1)
    minute = elem(total_minutes, 1)
    actual_hour = hour + div(minute, 60)
    actual_minute = rem(minute, 60)
    task_params_with_time = task_params
    |> Map.put("time_worked", %{"hour" => Integer.to_string(actual_hour), "minute" => Integer.to_string(actual_minute)})
    case Tasks.update_task(task, task_params_with_time) do
      {:ok, task} ->
        conn
        |> put_flash(:info, "Task updated successfully.")
        |> redirect(to: Routes.task_path(conn, :show, task))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", task: task, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    task = Tasks.get_task!(id)
    {:ok, _task} = Tasks.delete_task(task)

    conn
    |> put_flash(:info, "Task deleted successfully.")
    |> redirect(to: Routes.task_path(conn, :index))
  end
end

lib/task_tracker_web/views/task_view.ex
defmodule TaskTrackerWeb.TaskView do
  use TaskTrackerWeb, :view
end

lib/task_tracker_web/templates/task/edit.html.eex
<h1>Edit Task</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.task_path(@conn, :update, @task)) %>

<span><%= link "Back", to: Routes.task_path(@conn, :index) %></span>

lib/task_tracker_web/templates/task/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <%= hidden_input f, :time_worked %>

  <div class="form-group">
    <%= label f, "Task Name*" %>
    <%= text_input f, :title, class: "form-control" %>
    <%= error_tag f, :title %>
  </div>

  <div class="form-group">
    <%= label f, "Description*" %>
    <%= textarea f, :desc, class: "form-control" %>
    <%= error_tag f, :desc %>
  </div>

  <div class="form-group">
    <%= label f, :is_complete %>
    <%= checkbox f, :is_complete %>
    <%= error_tag f, :is_complete %>
  </div>

<%= if @task.id !== -1 do %>

<p>Start working on this task <i>(Note: This only works in minute increments and you cannot leave this page.)</i>:</p>
<button type="button"
        id="start-working-button"
        class="btn btn-secondary">Start Working</button>
<button type="button"
        id="stop-working-button"
        class="btn btn-secondary" style="display: none;"
        data-task-id="<%= @task.id %>">Stop Working</button>

<div style="margin-bottom: 15px;"></div>
<h4>Add time worked to this task:</h4>
<h6>(YYYY-MM-DD HH:MM:SS, YYYY-MM-DD HH:MM:SS); ...</h6>
<div style="margin-bottom: 10px">
    <%= if @is_task_assigned_to_user do %>
      <div>
        <textarea class="form-control" id="add-time-text-area"></textarea>

        <button id="add-time-button"
                data-task-id="<%= @task.id %>"
                class="btn btn-secondary"
                style="margin-top: 10px">Add Time</button>
      </div>
    <% else %>
      Cannot edit a task's time if you're not assigned to it
    <% end %>
</div>
<div class="form-group">
    <h4>Time Worked</h4>
    <table class="table table-striped">
      <thead class="thead-light">
        <tr>
          <th>Start Time</th>
          <th>End Time</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
<%= for time_block <- @time_blocks do %>
        <tr>
          <td><%= time_block.start_time %></td>
          <td><%= time_block.end_time %></td>
          <td>
            <%= link "Delete", to: Routes.time_block_path(@conn, :delete, time_block.id),
                method: :delete, data: [confirm: "Are you sure you want to delete"], class: "btn btn-danger btn-sm" %>
          </td>
        </tr>
<% end %>
      </tbody>
    </table>
</div>
<% end %>
  <div>
    <%= submit "Save", class: "btn btn-primary", id: "task-edit-save-button" %>
  </div>
<% end %>

lib/task_tracker_web/templates/task/index.html.eex
<div class="row">
    <div class="col-8">
      <h1>All Tasks</h1>
    </div>
    <div class="col-2">
      <%= if @current_user do %>
        <span><%= link "New Task", to: Routes.task_path(@conn, :new), class: "btn btn-primary" %></span>
      <% end %>
    </div>
</div>

<div class="row">
<%= for task <- @tasks do %>
    <div class="card col-5" style="margin: 5px">
      <div class="card-body">
        <h5 class="card-title"><%= link task.title, to: Routes.task_path(@conn, :show, task) %></h5>
        <%= if task.is_complete do %>
          <h6 class="card-subtitle mb-2 text-muted">Complete</h6>
        <% else %>
          <h6 class="card-subtitle mb-2 text-muted">Not Complete</h6>
        <% end %>
        <p class="card-text"><%= task.desc %></p>
        <%= link "Edit", to: Routes.task_path(@conn, :edit, task), class: "btn btn-link" %>
        <%= link "Delete", to: Routes.task_path(@conn, :delete, task), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-link" %>
      </div>
    </div>
<% end %>
</div>

lib/task_tracker_web/templates/task/new.html.eex
<h1>New Task</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.task_path(@conn, :create)) %>

<span><%= link "Back", to: Routes.task_path(@conn, :index) %></span>

lib/task_tracker_web/templates/task/show.html.eex
<h1><%= @task.title %></h1>

<ul class="list-group list-group-flush">

  <li class="list-group-item">
    <strong>Description:</strong>
    <%= @task.desc %>
  </li>

  <li class="list-group-item">
    <strong>Time worked (hh:mm):</strong>
    <%= @task.time_worked %>
  </li>

  <li class="list-group-item">
    <strong>Is complete:</strong>
    <%= @task.is_complete %>
  </li>

</ul>

<div style="margin-bottom: 20px"></div>

<%= if @current_user && @can_assigned_to_anyone do %>
  <div>
    <%= form_for @task_cset, Routes.assigned_task_path(@conn, :create), [class: "form-inline"], fn f -> %>

      <%= hidden_input f, :task_id %>

      <div class="form-group">
        <%= label f, "Assign to: " %>
        <%= select f, :user_id, @users %>
        <%= error_tag f, :user_id %>
      </div>

      <div>
        <%= submit "Assign to User", class: "btn btn-primary" %>

      </div>
    <% end %>
  </div>
<% end %>

<%= if @current_user do %>
  <span><%= link "Edit", to: Routes.task_path(@conn, :edit, @task), class: "btn btn-info" %></span>
<% end %>
<span><%= link "Go Back", to: Routes.task_path(@conn, :index), class: "btn btn-secondary" %></span>